from winappdbg import Debug
from MyEventHandler import MyEventHandler
import logging

def executor(cmd_line, offset, value_index, new_file, run_number, save_directory, logger):
    ''' Setup the debugger and the event handler. Execute the process, and after completion log the
        run-specific information, as well as check for any specific output generated by the event handler. '''
    
    # create a new process, run it
    handler = MyEventHandler(new_file, save_directory)   
    debug   = Debug(handler)
    process = debug.execl(cmd_line)
    debug.loop()

    # after completion, log the run
    output = '%s %d %s\n' % ('-'*10, run_number, '-'*10)
    output += 'Running : %s\n' % cmd_line
    output += 'run number = %d, offset = %d, value_index = %d' % (run_number, offset, value_index)   

    # if any signals are handled, debug output will be non-empty
    handler_output = handler.getOutput()
    if handler_output:
        output += 'handler_output = %s\n' % handler_output          #### HAVE THIS GENERATE A HIGHER LOG LEVEL
        print '\n'+'-'*20
        print '[!] Crash! Run number %d' % run_number
        print output
        print '\n'+'-'*20
    logger.log(logging.INFO, output)

